version: '3'
services:

  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs/:/etc/ssl/:ro
    ports:
      - 3001:3001
      - 3081:3081
    networks:
      testing_net:
          ipv4_address: 172.28.1.1

  lemonldap:
    image: coudot/lemonldap-ng:2.0.7
    volumes:
     - ./lemonldap_conf:/var/lib/lemonldap-ng/conf
    environment:
    - SSODOMAIN=lemonldap.localhost
    - LOGLEVEL=debug
    - PORTAL_HOSTNAME=myportal.lemonldap.localhost 
    - MANAGER_HOSTNAME=mymanager.lemonldap.localhost 
    - HANDLER_HOSTNAME=myhandler.lemonldap.localhost 
    - TEST1_HOSTNAME=mytest1.lemonldap.localhost 
    - TEST2_HOSTNAME=mytest2.lemonldap.localhost
    networks:
      testing_net:
          ipv4_address: 172.28.1.2

  oidc_node_client:
    build:
      context: ./node_oidc_client
      dockerfile: dockerfile
    volumes:
      - ./node_oidc_client/server.js:/app/server.js:ro    
    ports:
      - 4001:4001
    extra_hosts:
      - "myportal.lemonldap.localhost:172.28.1.1"
    networks:
      testing_net:
          ipv4_address: 172.28.1.3

networks:
  testing_net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16       

