version: '3'
services:

  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs/:/etc/ssl/:ro
    ports:
      # changing of the port here is not enough
      # also change it here:
      #   * in the file ./node_oidc_client/server.js 
      #   * in the file ./haproxy.cfg
      #   * in the lemonldap manager: General Parameters - Portal - URL 
      - 3001:3001
    networks:
      lemonldap_oidc_node_example_net:
          ipv4_address: 172.28.1.1

  lemonldap:
    image: coudot/lemonldap-ng:2.0.7
    volumes:
     - ./lemonldap_conf:/var/lib/lemonldap-ng/conf
    environment:
    - SSODOMAIN=lemonldap.localhost
    - LOGLEVEL=debug
    # change of host names makes only sense, before the first configuration file has been created, later go to 'Virtual Hosts' in manager
    # these values are only left here in case someone wants to delete all configuration files and setup a clean lemonldap configuration
    - PORTAL_HOSTNAME=myportal.lemonldap.localhost  
    - MANAGER_HOSTNAME=mymanager.lemonldap.localhost  
    - HANDLER_HOSTNAME=myhandler.lemonldap.localhost  
    - TEST1_HOSTNAME=mytest1.lemonldap.localhost 
    - TEST2_HOSTNAME=mytest2.lemonldap.localhost
    networks:
      lemonldap_oidc_node_example_net:
          ipv4_address: 172.28.1.2

  oidc_node_client:
    build:
      context: ./node_oidc_client
      dockerfile: dockerfile
    volumes:
      - ./node_oidc_client/server.js:/app/server.js:ro    
    ports:
      # changing of the port here is not enough
      # also change it in the lemonldap manager under:
      #   * OpenID Connect Relying Parties - (client name) - Options - Allowed redirection addresses for login 
      #   * General Parameters - Advanced Parameters - Security - Content Security Policy - Form Destinations
      - 4001:4001
    extra_hosts:
      - "myportal.lemonldap.localhost:172.28.1.1"
    networks:
      lemonldap_oidc_node_example_net:
          ipv4_address: 172.28.1.3

networks:
  lemonldap_oidc_node_example_net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16       

